cp-32: [BUG] Header component is not responsive in Safari browser
BinaryStudioAcademy/bsa-2023-calmpal pull request #111
Opened 2023-08-30 01:08 UTC by juanc-escobar

The header component was not responsive in the Safari browser, The heather was implemented with flex, so I gave it a max width and fixed the overflows problems for the body, app-container, and body-container since it showed me overflow on Safari. I don't have Mac OS I use an emulator so results may not be 100% accurate but I believe this solved the issue.

2023-08-30 06:46 UTC, iamAlinaaa reviewed
code looks neat )does it work good on your computer?

2023-08-30 07:06 UTC, fshabanov commented
Could you, please, share the screenshots?

2023-08-30 12:08 UTC, juanc-escobar commented
> Could you, please, share the screenshots? 

Sure! Here are some screenshots at less than 950px in Webkit (Safari) @fshabanov @iamAlinaaa 

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/5d58019d-14f2-4ff6-b24a-439451b37b1e)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/eb320ee7-c6bd-4915-8be2-6c4a17182007)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/3c231c1a-9675-4f56-8962-551a37873c9c)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/fa8c4b0a-412b-4d0c-9a92-b1dcfcd093e4)

2023-08-30 13:05 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-08-30 13:55 UTC, OlesiaTr submitted a review, later dismissed

2023-08-30 18:18 UTC, fshabanov submitted a review, later dismissed

2023-08-30 18:20 UTC, v0ldemar01 submitted a review, later dismissed

2023-08-30 18:47 UTC, iamAlinaaa submitted a review, later dismissed
looks good

2023-08-30 20:45 UTC, Nanaier submitted a review, later dismissed

2023-08-31 05:14 UTC, juanc-escobar commented
ci Expected — Waiting for status to be reported
ci-pr Expected — Waiting for status to be reported

I updated the branch with the latest changes but had a lot of trouble with docker and node modules so I had to delete and reinstall, it works in my local environment and I did the push but the ci and ci-pr won't change status.

2023-08-31 09:50 UTC, Liza-Veis commented
you need to fix conflicts to make it work

2023-08-31 13:23 UTC, juanc-escobar commented
@Liza-Veis 

I reverted the changes and installed @esbuild/win32-x64 as dependency, also pulled the latest changes in but didn't have a merge conflict. 

now it's showing me this in the PR:

Conflicting files
frontend/src/libs/components/app/styles.module.scss
package-lock.json

but does not show me the conflict and vs. code after pulling the latest changes didn't show me conflict how should I solve this?

2023-08-31 16:08 UTC, Liza-Veis commented
which command did you use to pull new changes?

2023-08-31 16:49 UTC, juanc-escobar commented
@Liza-Veis

git pull origin fix/cp-32-header-component

2023-08-31 17:02 UTC, fshabanov commented
> @Liza-Veis
> 
> git pull origin fix/cp-32-header-component

@juanc-escobar you should use `git pull origin development`

2023-08-31 19:10 UTC, juanc-escobar commented
thanks for the clarification. @fshabanov @Liza-Veis 

I was able to successfully merge the latest changes.

2023-08-31 19:38 UTC, BrianSammit approved these changes, later dismissed

2023-08-31 23:48 UTC, Liza-Veis requested changes

2023-08-31 23:48 UTC, Liza-Veis commented on package.json
> +    "esbuild": "0.19.2",
if you remove node_modules and reinstall them again this should work without this dependency, maybe we will add it later but only for frontend
```suggestion
```

2023-09-01 01:35 UTC, juanc-escobar commented
@Liza-Veis  I uninstalled esbuild ✅

2023-09-01 01:53 UTC, Liza-Veis approved these changes

2023-09-01 07:10 UTC, fshabanov approved these changes

2023-09-01 07:12 UTC, merged