cp-103: Add dropdown menu
BinaryStudioAcademy/bsa-2023-calmpal pull request #118
Opened 2023-08-30 14:18 UTC by Nanaier

2023-08-30 15:01 UTC, OlesiaTr submitted a review, later dismissed

2023-08-30 16:11 UTC, v0ldemar01 requested changes

2023-08-30 16:11 UTC, v0ldemar01 commented on frontend/src/libs/components/dropdown-menu/dropdown-menu.tsx
> +  const toggleDropdown = useCallback((): void => {
Please follow rule about handler's naming

2023-08-30 16:24 UTC, Nanaier commented on frontend/src/libs/components/dropdown-menu/dropdown-menu.tsx
> +  const toggleDropdown = useCallback((): void => {
done!

2023-08-30 16:51 UTC, Liza-Veis requested changes

2023-08-30 16:51 UTC, Liza-Veis commented on frontend/src/libs/components/dropdown-menu/dropdown-menu.tsx
> +const Dropdown: React.FC<Routes> = ({ routes }) => {
Component name should be the same as file name
```suggestion
const DropdownMenu: React.FC<Routes> = ({ routes }) => {
```

2023-08-30 16:51 UTC, Liza-Veis commented on frontend/src/libs/components/dropdown-menu/styles.module.scss
> +@media (width > 480px) {
let's make all queries in the same style
```suggestion
@media (width < 480px) {
```

2023-08-30 16:51 UTC, Liza-Veis commented on frontend/src/libs/components/header/styles.module.scss
> +@media (width <= 480px) {
```suggestion
@media (width < 480px) {
```

2023-08-30 18:29 UTC, fshabanov requested changes

2023-08-30 18:29 UTC, fshabanov commented on frontend/src/libs/types/route/route.type.ts
> +import { type ValueOf } from '../types.js';
This will cause a circular dependency

2023-08-30 19:51 UTC, Nanaier commented
@Liza-Veis hey, as you can see I have some conflicts rn - Would it be okay if I resolve them based on the clean-up of the code done by my other teammate? So there would be no code showcasing how the dropdown works on the root page since it would be cleaned up, but you can see the functionality on the demo

2023-08-30 22:19 UTC, Ekit18 approved these changes, later dismissed

2023-08-30 22:23 UTC, Ekit18 commented on frontend/src/libs/components/dropdown-menu/dropdown-menu.tsx
> +    setOpen(!isOpen);
may be its better to write smth like this: setOpen((previous)=> !previous)

2023-08-30 22:26 UTC, Dmytro-Kucherenko reviewed
Nice work)

2023-08-30 22:26 UTC, Dmytro-Kucherenko commented on frontend/src/libs/components/dropdown-menu/styles.module.scss
> +hr {
According to the rule B10 we can't use tag names in styles, only classes

2023-08-30 22:26 UTC, Dmytro-Kucherenko commented on frontend/src/libs/components/sidebar/styles.module.scss
>  .icons-container a {
The same with tag names

2023-08-30 23:26 UTC, Vika030718 approved these changes, later dismissed

2023-08-31 09:21 UTC, HIMDanny submitted a review, later dismissed

2023-08-31 09:21 UTC, HIMDanny commented on frontend/src/libs/components/dropdown-menu/dropdown-menu.tsx
> +        <span className={styles['bar']} />
according to the **B4** rule, we can reduce the number of spans and use pseudo-elements instead

2023-08-31 11:53 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-08-31 15:35 UTC, Liza-Veis approved these changes

2023-08-31 15:41 UTC, fshabanov approved these changes

2023-08-31 15:42 UTC, merged