cp-131: Mobile Text Input Field When Error
BinaryStudioAcademy/bsa-2023-calmpal pull request #137
Opened 2023-08-31 15:40 UTC by iamAlinaaa

Successfully solved bag from this issue : #131 
![Снимок экрана 2023-08-31 183317](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/927ac1fd-f057-4867-b675-815737eb86fc)

2023-08-31 17:00 UTC, fshabanov requested changes

2023-08-31 17:00 UTC, fshabanov commented on mobile/src/libs/components/input/input.tsx
> +          hasError && isFocused && styles.filledInput,
Now basically `!hasError && isFocused` and `hasError && isFocused` have the same styles, we can just put `isFocused && styles.filledInput`.
And I think if filledInput is for focused input, let's rename it to `focusedInput`

2023-08-31 17:22 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-08-31 18:13 UTC, fshabanov approved these changes, later dismissed

2023-08-31 18:38 UTC, Liza-Veis submitted a review, later dismissed

2023-08-31 21:59 UTC, Vika030718 submitted a review, later dismissed

2023-09-01 07:33 UTC, Liza-Veis approved these changes

2023-09-01 07:58 UTC, merged