cp-145: Replace App Logo
BinaryStudioAcademy/bsa-2023-calmpal pull request #146
Opened 2023-09-01 10:55 UTC by danilittaa

- replaced app logo on auth screens
- replaced app icon
- replaced splash screen
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/108797614/3bb12840-d082-4055-821b-37e2213be041)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/108797614/23e62276-28d6-4a5f-b644-84e278a5186d)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/108797614/44d2f45a-7e73-4b41-8848-a5e1dbd8b5e7)

2023-09-01 11:08 UTC, HIMDanny submitted a review, later dismissed

2023-09-01 11:56 UTC, iamAlinaaa submitted a review, later dismissed
looks great 🤩

2023-09-01 12:02 UTC, Vika030718 submitted a review, later dismissed

2023-09-01 12:05 UTC, v0ldemar01 submitted a review, later dismissed

2023-09-01 12:15 UTC, fshabanov submitted a review, later dismissed

2023-09-01 13:11 UTC, Dmytro-Kucherenko submitted a review, later dismissed

2023-09-02 03:52 UTC, BrianSammit submitted a review, later dismissed

2023-09-02 09:32 UTC, Dmytro-Kucherenko approved these changes, later dismissed

2023-09-02 17:40 UTC, fshabanov submitted a review, later dismissed

2023-09-03 11:49 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-09-03 15:04 UTC, Liza-Veis requested changes

2023-09-03 15:04 UTC, Liza-Veis commented on mobile/src/screens/auth/components/label/label.tsx
> +import LogoImage from '#assets/img/logo.png';
```suggestion
import logo from '#assets/img/logo.png';
```

2023-09-03 15:20 UTC, Liza-Veis approved these changes

2023-09-03 15:21 UTC, merged