cp-150: * renamed chat list to chat
BinaryStudioAcademy/bsa-2023-calmpal pull request #164
Opened 2023-09-03 11:30 UTC by iamAlinaaa

Successfully renamed 'Chat list' to 'Chat'

![Снимок экрана 2023-09-03 142512](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/c6de80af-3958-413e-a05f-c568c7872ac6)
![Снимок экрана 2023-09-03 142529](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/091f93c4-e93a-4a7b-b058-6f628fb0ee41)

2023-09-03 11:33 UTC, Dmytro-Kucherenko approved these changes, later dismissed

2023-09-03 11:36 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-09-03 15:00 UTC, Liza-Veis requested changes

2023-09-03 15:00 UTC, Liza-Veis commented on mobile/src/libs/enums/navigation/main-screen-name.enum.ts
> +  CHAT_LIST: 'Chat',
```suggestion
  CHAT: 'Chat',
```

2023-09-03 18:32 UTC, iamAlinaaa commented on mobile/src/libs/enums/navigation/main-screen-name.enum.ts
> +  CHAT_LIST: 'Chat',
@Liza-Veis there will be separate screen named CHAT from #60 , thats why i left CHAT_LIST 
![Снимок экрана 2023-09-03 212948](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/68d818e7-6b2e-44a9-a4ff-300af0386d1a)

2023-09-03 19:17 UTC, Liza-Veis commented on mobile/src/libs/enums/navigation/main-screen-name.enum.ts
> +  CHAT_LIST: 'Chat',
It's okay if we have screens with the same name in different navigations. Even if it was a problem, it doesn't matter how we name the keys of the enum, what matters is how we name the values of the enum

2023-09-03 19:27 UTC, iamAlinaaa commented on mobile/src/libs/enums/navigation/main-screen-name.enum.ts
> +  CHAT_LIST: 'Chat',
@Liza-Veis renamed CHAT_LIST to CHAT

2023-09-03 19:32 UTC, Dmytro-Kucherenko approved these changes, later dismissed

2023-09-04 09:51 UTC, fshabanov submitted a review, later dismissed

2023-09-04 10:50 UTC, v0ldemar01 approved these changes, later dismissed

2023-09-04 21:47 UTC, Vika030718 approved these changes, later dismissed

2023-09-05 07:54 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-09-05 13:08 UTC, OlesiaTr submitted a review, later dismissed

2023-09-05 14:51 UTC, Liza-Veis submitted a review, later dismissed

2023-09-05 15:36 UTC, fshabanov submitted a review, later dismissed

2023-09-05 17:12 UTC, Nanaier approved these changes, later dismissed

2023-09-05 21:47 UTC, Dmytro-Kucherenko approved these changes

2023-09-06 08:20 UTC, OlesiaTr approved these changes

2023-09-06 21:25 UTC, Liza-Veis approved these changes

2023-09-06 21:33 UTC, merged