cp-246: White circles around sidebar options don't have all the same size
BinaryStudioAcademy/bsa-2023-calmpal pull request #288
Opened 2023-09-14 03:12 UTC by juanc-escobar

I fixed these issues:
The icons didn't have the same size.  
The link was not the same shape as the button container.  
The icon container didn't have a fixed width.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/2f784c61-de88-4d7c-b33e-6fd0730a9462)

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/247b6fae-bc17-4770-ac35-8fd0077c4ba6)

2023-09-14 08:27 UTC, OlesiaTr submitted a review, later dismissed

2023-09-14 10:59 UTC, Dmytro-Kucherenko commented on frontend/src/libs/components/icon/icon.tsx
> +  height?: string | number;
It's better to make these properties `number` only and then convert them to `string` and add `px`

2023-09-15 06:35 UTC, Dmytro-Kucherenko commented on frontend/src/libs/components/icon/icon.tsx
> +    height: height ? `${height}px` : undefined,
We're trying not to set undefined, maybe null if it's allowed or empty single quote

2023-09-15 16:21 UTC, Liza-Veis requested changes

2023-09-15 16:21 UTC, Liza-Veis commented on frontend/src/libs/components/icon/icon.tsx
> +    height: height ? `${height}px` : undefined,
can't we pass width and height as attributes instead of styles?

2023-09-16 11:42 UTC, OlesiaTr approved these changes

2023-09-16 11:45 UTC, Dmytro-Kucherenko approved these changes

2023-09-16 15:43 UTC, v0ldemar01 approved these changes

2023-09-17 10:59 UTC, Ekit18 approved these changes

2023-09-17 14:07 UTC, fshabanov approved these changes

2023-09-18 09:04 UTC, iamAlinaaa approved these changes

2023-09-18 17:16 UTC, Liza-Veis approved these changes

2023-09-18 17:20 UTC, merged