cp-272: Create Chat Functionality
BinaryStudioAcademy/bsa-2023-calmpal pull request #298
Opened 2023-09-15 14:36 UTC by danilittaa

I am waiting for the backend implemention to complete my task

2023-09-16 11:57 UTC, OlesiaTr approved these changes, later dismissed

2023-09-16 16:13 UTC, v0ldemar01 requested changes

2023-09-16 16:13 UTC, v0ldemar01 commented on mobile/src/libs/components/button/button.tsx
> +      {iconName &&
Prevent complexity with double ternary operator

2023-09-16 16:13 UTC, v0ldemar01 commented on mobile/src/libs/components/button/button.tsx
> +            color={isAddButton ? AppColor.BLUE_300 : AppColor.GRAY_400}
Button doesn't know of how will we use it

2023-09-17 10:58 UTC, Ekit18 approved these changes, later dismissed

2023-09-18 08:54 UTC, iamAlinaaa submitted a review, later dismissed
looks good to me

2023-09-18 12:16 UTC, Liza-Veis requested changes

2023-09-18 12:16 UTC, Liza-Veis commented on mobile/src/libs/components/button/button.tsx
> +    if (iconName) {
check this where you call this function
```suggestion
```

2023-09-18 13:15 UTC, OlesiaTr approved these changes, later dismissed

2023-09-18 17:24 UTC, Liza-Veis commented on mobile/src/screens/chat-list/chat-list.tsx
> +  }, [chats, handleRedirectToChat]);
```suggestion
  }, [chatsLength, handleRedirectToChat]);
```

2023-09-18 17:28 UTC, Liza-Veis requested changes

2023-09-18 17:28 UTC, Liza-Veis commented on mobile/src/screens/chat/chat.tsx
> +        void dispatch(chatsActions.createChat({ message: 'New Chat' }));
we should pass user first message, not mocked data

2023-09-19 07:42 UTC, v0ldemar01 submitted a review, later dismissed

2023-09-19 12:10 UTC, OlesiaTr approved these changes, later dismissed

2023-09-19 14:13 UTC, Liza-Veis submitted a review, later dismissed

2023-09-19 14:14 UTC, dmytro-kucherenko commented on mobile/src/libs/components/button/button.tsx
> +          name={iconName ?? 'play'}
```suggestion
          name={iconName as iconName}
```
In that stage you already have non nullable iconName because of the boolean below

2023-09-19 14:41 UTC, Liza-Veis requested changes

2023-09-19 14:41 UTC, Liza-Veis commented on mobile/src/libs/components/button/button.tsx
> +          color={color ?? isRounded ? AppColor.BLUE_200 : AppColor.GRAY_400}
let's use only one color, without dependence on the isRounded property

2023-09-19 15:34 UTC, Liza-Veis approved these changes

2023-09-19 15:34 UTC, merged