cp-246: changed icon size in chat and profile
BinaryStudioAcademy/bsa-2023-calmpal pull request #357
Opened 2023-09-22 01:02 UTC by juanc-escobar

*made the chat icon a bit smaller and my profile icon a bit larger
 *added functionality to customize each icon if needed. 
 
 
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/17f428da-4a98-4b0d-a1f7-6c2cb531537c)

2023-09-22 08:11 UTC, danilittaa commented on frontend/src/libs/components/navigation-menu/libs/constants.ts
> +
I think it would be better to rename these constants to 'DEFAULT_ICON_WIDTH'

2023-09-22 13:27 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-09-22 13:51 UTC, BrianSammit submitted a review, later dismissed

2023-09-23 11:18 UTC, v0ldemar01 requested changes

2023-09-23 11:18 UTC, v0ldemar01 commented on frontend/src/libs/components/navigation-menu/libs/constants.ts
libs/constants/constants

2023-09-23 14:35 UTC, Liza-Veis requested changes

2023-09-23 14:35 UTC, Liza-Veis commented on frontend/src/libs/components/navigation-menu-wrapper/libs/constants.ts
> +    iconHeight: 20,
all of them should have the same width and height - 24
```suggestion
```

2023-09-23 14:35 UTC, Liza-Veis commented on frontend/src/libs/components/navigation-menu/navigation-menu.tsx
> +                      width={route.iconWidth ?? DEFAULT_ICON_WIDTH}
check that this won't broken icons in other places

2023-09-24 05:17 UTC, juanc-escobar commented
adjusted de icons to be all close to 24 x 24 according to what was requested:

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/ac61dacd-8b4e-4d39-8005-29a3122b2872)


![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/ac6ac8df-6718-4a7d-bd16-cafde045073b)

2023-09-24 10:07 UTC, Liza-Veis requested changes

2023-09-24 10:07 UTC, Liza-Veis commented on frontend/src/libs/types/route/route.type.ts
> +  iconHeight?: number;
```suggestion
```

2023-09-24 19:43 UTC, OlesiaTr approved these changes

2023-09-25 12:37 UTC, Dmytro-Kucherenko approved these changes

2023-09-26 05:27 UTC, Liza-Veis approved these changes

2023-09-26 05:27 UTC, merged