cp-170: Add Meditation Player Layout
BinaryStudioAcademy/bsa-2023-calmpal pull request #384
Opened 2023-09-24 10:38 UTC by danilittaa

- fixed styles
- added getFormattedTime helper (instead of using the one already existing in the shared folder, because it turns out that the existing helper was breaking the time display. Besides, I don't really need that other helper because it uses 'getTimezoneOffset,' which I don't need at all)

2023-09-24 12:27 UTC, v0ldemar01 requested changes

2023-09-24 12:27 UTC, v0ldemar01 commented on mobile/src/libs/helpers/get-formatted-time/get-formatted-time.helper.ts
We need to figure out how to accommodate that helper

2023-09-24 12:41 UTC, danilittaa commented on mobile/src/libs/helpers/get-formatted-time/get-formatted-time.helper.ts
Could you please explain what you mean?

2023-09-24 14:07 UTC, v0ldemar01 commented on mobile/src/libs/helpers/get-formatted-time/get-formatted-time.helper.ts
We should use this one for frontend and mobile indeed. So Looks like the issue is related to timezone of prod mode.

2023-09-24 14:34 UTC, danilittaa commented on mobile/src/libs/helpers/get-formatted-time/get-formatted-time.helper.ts
But I really don't need to take into account the time zone, as it simply displays the track's time. If I don't understand something, please correct me

2023-09-24 14:53 UTC, v0ldemar01 commented on mobile/src/libs/helpers/get-formatted-time/get-formatted-time.helper.ts
The app can be deployed into any timezone, so we need to in touch with it

2023-09-24 20:05 UTC, OlesiaTr approved these changes, later dismissed

2023-09-27 07:33 UTC, iamAlinaaa approved these changes, later dismissed

2023-09-28 13:46 UTC, Dmytro-Kucherenko commented on mobile/src/libs/components/player/components/controls/controls.tsx
> +    }, []),
Shouldn't `setIsPlaying` be in dependencies? The same with dependencies of `useCallback`'s in other places

2023-09-28 13:46 UTC, Dmytro-Kucherenko commented on mobile/src/libs/components/player/player.tsx
> +      if (nextAppState === 'background') {
May we create `AppState` enum for that reason?

2023-09-28 13:46 UTC, Dmytro-Kucherenko commented on mobile/src/libs/helpers/get-formatted-time/get-formatted-time.helper.ts
We have helper with the same name in shared folder, is they're the different things?

2023-09-29 07:19 UTC, v0ldemar01 approved these changes

2023-09-29 07:20 UTC, v0ldemar01 requested changes
Small typo issue

2023-09-29 07:20 UTC, v0ldemar01 commented on mobile/src/libs/packages/player/player.package.ts
> +  public startPlayling = async (): Promise<void> => {
```suggestion
  public startPlaying = async (): Promise<void> => {
```

2023-09-29 07:52 UTC, v0ldemar01 approved these changes

2023-09-29 07:53 UTC, fshabanov approved these changes

2023-09-29 08:02 UTC, merged