cp-56: Add chats and chat messages tables
BinaryStudioAcademy/bsa-2023-calmpal pull request #58
Opened 2023-08-23 01:10 UTC by ossavemu

I have added the tables that chats and chat messages, creating the corresponding migration files. I created a helper to avoid repeating code and updated the default migration to use the helper.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90299049/80bd3eb1-2a26-4591-a888-c292280109e8)

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90299049/6e735c51-efda-4ba9-b058-76913fbd25ea)

2023-08-23 04:42 UTC, Xxandder commented on backend/src/db/migrations/20230215152530_add_users_table.ts
Hi, I think here you need to get rid of TableNames and UserTableColumns enums.  I had the same problem : [here](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/46#discussion_r1301949765)
And the same for other another migration

2023-08-23 05:10 UTC, Xxandder commented on backend/src/db/migrations/20230822123000_add_chat_messages_table.ts
You also need to add onDelete and onUpdate for foreign columns so messages will be automaticly deleted/updated when a chat or sender is deleted/updated

2023-08-23 05:12 UTC, Xxandder commented on backend/src/db/migrations/20230822123000_add_chat_messages_table.ts
Sorry for missing changes block in my comment. I just hadn't knew about how to add it

2023-08-23 05:22 UTC, Liza-Veis commented on backend/src/db/migrations/20230215152530_add_users_table.ts
Agree

2023-08-23 06:57 UTC, v0ldemar01 requested changes

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/db/helpers/migration-helper.ts
> +function createTableWithCommonColumns(
As @Xxandder mentioned, we need to create an independent migrations. So your idea is good, bit not suitable for migrations

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/db/migrations/20230215152530_add_users_table.ts
> +const up = createTableWithCommonColumns(
It is not a good idea to modify existing migrations

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/chat-messages-table-columns.ts
> +};
```suggestion
} as const;
```

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/chats-table-columns.ts
> +};
```suggestion
} as const;
```

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/common-table-columns.ts
> +};
```suggestion
} as const;
```

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/chats-table-columns.ts
> +const ChatsTableColumns = {
Enums should be in plural form

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/chat-messages-table-columns.ts
> +const ChatMessagesTableColumns = {
Enums should be in plural form

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/table-names.ts
> +const TableNames = {
We already have DatabaseTableName

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/user-table-columns.ts
> +const UserTableColumns = {
It's not a correct destination for that enum

2023-08-23 06:57 UTC, v0ldemar01 commented on backend/src/libs/enums/user-table-columns.ts
> +const UserTableColumns = {
And please contact with guys which are have the tasks related to user table columns, maybe they are done with it

2023-08-23 15:26 UTC, ossavemu commented on backend/src/libs/enums/table-names.ts
> +const TableNames = {
I used the cp-14: Adding registry functionality #46 as an example when adding the enum

2023-08-23 15:29 UTC, v0ldemar01 requested changes

2023-08-23 15:29 UTC, v0ldemar01 commented on backend/src/libs/enums/database-table-name.enum.ts
<img width="630" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/43109766/a54deddc-a1bb-4a80-b3dd-32b1fb29deb9">

2023-08-23 15:29 UTC, v0ldemar01 commented on backend/src/libs/enums/table-columns/chat-messages-table-column.enum.ts
> +const ChatMessagesTableColumn = {
Please move to appropriate package

2023-08-23 21:25 UTC, Liza-Veis approved these changes
Good job 🙌

2023-08-24 06:46 UTC, Nanaier approved these changes

2023-08-24 07:44 UTC, fshabanov approved these changes

2023-08-24 07:46 UTC, v0ldemar01 approved these changes

2023-08-24 08:47 UTC, Liza-Veis approved these changes

2023-08-24 08:47 UTC, merged