cp-76: Add Splash Screen
BinaryStudioAcademy/bsa-2023-calmpal pull request #83
Opened 2023-08-26 18:55 UTC by danilittaa

- Added splash screen
- Automatically dissappers when application is loaded
- There is no design for this screen, so I improvised a little)

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/108797614/4f3d9e43-45ef-420b-932e-ac5bea5d4e8c)

2023-08-26 19:02 UTC, Liza-Veis requested changes
I like the design

2023-08-26 19:02 UTC, Liza-Veis commented on mobile/src/libs/components/app/app.tsx
> +  SplashScreen.hide();
all side effects should be in useEffect

2023-08-26 20:17 UTC, Liza-Veis approved these changes

2023-08-27 05:29 UTC, fshabanov approved these changes

2023-08-27 05:30 UTC, v0ldemar01 approved these changes

2023-08-27 07:54 UTC, iamAlinaaa approved these changes
Looks great 🤩

2023-08-27 15:22 UTC, merged