cp-25:  Mobile Protected Routing
BinaryStudioAcademy/bsa-2023-calmpal pull request #92
Opened 2023-08-28 16:22 UTC by danilittaa

- created ProtectedRoute as described in issue

2023-08-28 16:29 UTC, v0ldemar01 requested changes

2023-08-28 16:29 UTC, v0ldemar01 commented on mobile/src/libs/components/protected-route/protected-route.tsx
> +      navigation.navigate('Sign In');
Please add an enum value

2023-08-28 16:32 UTC, fshabanov requested changes

2023-08-28 16:32 UTC, fshabanov commented on mobile/src/libs/components/app/app.tsx
> +          </ProtectedRoute>
We don't want to make every screen protected. Screens like Sign in and Sign up should not be protected.

2023-08-28 16:32 UTC, fshabanov commented on mobile/src/libs/components/protected-route/protected-route.tsx
> +type Proptertis = {
```suggestion
type Properties = {
```

2023-08-28 16:32 UTC, fshabanov commented on mobile/src/libs/components/protected-route/protected-route.tsx
> +  const hasUser = Boolean(user?.id);
```suggestion
  const hasUser = Boolean(user);
```

2023-08-28 18:23 UTC, Liza-Veis requested changes

2023-08-28 18:23 UTC, Liza-Veis commented on mobile/src/libs/components/protected-route/protected-route.tsx
> +  const { user } = useAppSelector((store) => store.auth);
```suggestion
  const { authenticatedUser } = useAppSelector(({auth}) => ({
    authenticatedUser: auth.authenticatedUser
  }));
```

2023-08-29 08:23 UTC, OlenaYatseniuk submitted a review, later dismissed

2023-08-29 08:54 UTC, Liza-Veis approved these changes

2023-08-29 09:38 UTC, Liza-Veis requested changes

2023-08-29 09:38 UTC, Liza-Veis commented on mobile/src/navigations/root/root.tsx
> +          <ProtectedRoute>
Let's leave this component but don't wrap anything for now, we will use it a bit later

2023-08-29 09:56 UTC, Liza-Veis approved these changes

2023-08-29 09:56 UTC, merged